### ISSUE TITLE
Build fails with RediStack 1.0.0-beta.1

### ISSUE THREAD

**Issue by andreigherghe** [vapor/redis-kit#34]
Since RediStack is imported like this, on a new deployment, it updated to the latest beta version, which does not compile.
`.package(url: "https://gitlab.com/mordil/RediStack.git", from: "1.0.0-alpha.8"),`

Workaround:
Add to main Package.swift:
`.package(url: "https://gitlab.com/mordil/RediStack.git", .exact("1.0.0-alpha.10")),`
![unknown](https://user-images.githubusercontent.com/18578250/91823580-199df380-ec42-11ea-84e3-b9ddb07645db.png)

**Comment by Mordil** [comment]
@andreigherghe Fixed with [`1.0.0-beta.5.1`](https://github.com/vapor/redis-kit/releases/tag/1.0.0-beta.5.1)

The **Vapor/Redis** package should be updated soon to drop this intermediate package and rely on **RediStack** directly.

Are you using **RedisKit** directly, or did this come up while using **Vapor/Redis**?

If you're using this package directly, you should switch to using **RediStack** directly, as this package is being deprecated.
